---
- hosts: 
    - all
  gather_facts: false
  tasks:
    - name: Check /boot Space
      shell: df -h /boot
      register: boot_space
      
    - name: Display /boot Space
      debug:
        var: boot_space.stdout_lines
